In [2]:
import numpy as np

# Creating a 1 Dimension Array

In [8]:
a=np.array([1,2,3])

In [ ]:
a

In [11]:
# create an zero array with 3 elements 
z=np.zeros(3)
z

array([0., 0., 0.])

In [12]:
# create an array with ones 4 elements
o=np.ones(4)
o

array([1., 1., 1., 1.])

In [13]:
# create an empty array with 5 elements 
e=np.empty(5)

In [14]:
e

array([ 9.68499543e+139,  7.69253479e+250, -3.42740238e-294,
        1.28242775e+291,  2.25170504e+289])

In [16]:
# with range of elements 
e=np.arange(6)

In [17]:
e

array([0, 1, 2, 3, 4, 5])

In [20]:
a= np.array([1,2,3])
b=np.ones(3)
c= np.zeros(4)
d=np.empty(2)
a,b,c,d

(array([1, 2, 3]),
 array([1., 1., 1.]),
 array([0., 0., 0., 0.]),
 array([2.53198806e-041, 1.06891822e-175]))

In [21]:
# with specific range of elements
r=np.arange(2,20)
r

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [23]:
# continue with 2 steps 
r=np.arange(2,20,2)
r

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])